"""create alerte table

Revision ID: 15187457a65c
Revises: 4c61ac047673
Create Date: 2025-03-10 10:04:14.722649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15187457a65c'
down_revision: Union[str, None] = '4c61ac047673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categorie_Alerte',
    sa.Column('idCategorieAlerte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idCategorieAlerte')
    )
    op.create_index(op.f('ix_Categorie_Alerte_idCategorieAlerte'), 'Categorie_Alerte', ['idCategorieAlerte'], unique=False)
    op.create_table('Alertes',
    sa.Column('idAlerte', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('categorie_alert_id', sa.Integer(), nullable=False),
    sa.Column('date_alerte', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_alert_id'], ['Categorie_Alerte.idCategorieAlerte'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('idAlerte')
    )
    op.create_index(op.f('ix_Alertes_idAlerte'), 'Alertes', ['idAlerte'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Alertes_idAlerte'), table_name='Alertes')
    op.drop_table('Alertes')
    op.drop_index(op.f('ix_Categorie_Alerte_idCategorieAlerte'), table_name='Categorie_Alerte')
    op.drop_table('Categorie_Alerte')
    # ### end Alembic commands ###
