"""create categorie_site table

Revision ID: 28b57801e022
Revises: 
Create Date: 2025-02-24 11:04:45.876934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b57801e022'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categorie_Site',
    sa.Column('idCategorieSite', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idCategorieSite')
    )
    op.create_index(op.f('ix_Categorie_Site_idCategorieSite'), 'Categorie_Site', ['idCategorieSite'], unique=False)
    op.create_table('Site',
    sa.Column('idSite', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('idCategorieSite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCategorieSite'], ['Categorie_Site.idCategorieSite'], ),
    sa.PrimaryKeyConstraint('idSite')
    )
    op.create_index(op.f('ix_Site_idSite'), 'Site', ['idSite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Site_idSite'), table_name='Site')
    op.drop_table('Site')
    op.drop_index(op.f('ix_Categorie_Site_idCategorieSite'), table_name='Categorie_Site')
    op.drop_table('Categorie_Site')
    # ### end Alembic commands ###
