"""create consommation table

Revision ID: 4e865edbda35
Revises: ddfe1629353f
Create Date: 2025-02-26 12:58:59.595410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e865edbda35'
down_revision: Union[str, None] = 'ddfe1629353f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Consommation',
    sa.Column('idConsommation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('jour', sa.Date(), nullable=False),
    sa.Column('idAppareil', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idAppareil'], ['Appareil.idAppareil'], ),
    sa.PrimaryKeyConstraint('idConsommation')
    )
    op.create_index(op.f('ix_Consommation_idConsommation'), 'Consommation', ['idConsommation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Consommation_idConsommation'), table_name='Consommation')
    op.drop_table('Consommation')
    # ### end Alembic commands ###
