"""Create invitation table

Revision ID: 683ca41d323b
Revises: 77f9f5a1fea7
Create Date: 2025-02-28 11:00:34.222108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683ca41d323b'
down_revision: Union[str, None] = '77f9f5a1fea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['Site.idSite'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_Invitation_email'), 'Invitation', ['email'], unique=False)
    op.create_index(op.f('ix_Invitation_id'), 'Invitation', ['id'], unique=False)
    op.create_table('user_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['Site.idSite'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sites_id'), 'user_sites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sites_id'), table_name='user_sites')
    op.drop_table('user_sites')
    op.drop_index(op.f('ix_Invitation_id'), table_name='Invitation')
    op.drop_index(op.f('ix_Invitation_email'), table_name='Invitation')
    op.drop_table('Invitation')
    # ### end Alembic commands ###
