"""create site table

Revision ID: b1368caaccc1
Revises: 28b57801e022
Create Date: 2025-02-24 11:10:44.737935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1368caaccc1'
down_revision: Union[str, None] = '28b57801e022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Site', sa.Column('idUser', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Site', 'users', ['idUser'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Site', type_='foreignkey')
    op.drop_column('Site', 'idUser')
    # ### end Alembic commands ###
