"""update appareil table

Revision ID: ba12329232a2
Revises: 4e865edbda35
Create Date: 2025-02-26 13:00:42.316136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba12329232a2'
down_revision: Union[str, None] = '4e865edbda35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Appareil', sa.Column('idSite', sa.Integer(), nullable=False))
    op.drop_constraint('Appareil_idUser_fkey', 'Appareil', type_='foreignkey')
    op.create_foreign_key(None, 'Appareil', 'Site', ['idSite'], ['idSite'])
    op.drop_column('Appareil', 'idUser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Appareil', sa.Column('idUser', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Appareil', type_='foreignkey')
    op.create_foreign_key('Appareil_idUser_fkey', 'Appareil', 'users', ['idUser'], ['id'])
    op.drop_column('Appareil', 'idSite')
    # ### end Alembic commands ###
