"""update site table

Revision ID: be2652bb2d77
Revises: 
Create Date: 2025-03-20 17:53:46.448125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2652bb2d77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Appareil_idCategorieAppareil_fkey', 'Appareil', type_='foreignkey')
    op.create_foreign_key(None, 'Appareil', 'Categorie_Appareil', ['idCategorieAppareil'], ['idCategorieAppareil'])
    op.add_column('Site', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('Site', sa.Column('longtitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Site', 'longtitude')
    op.drop_column('Site', 'latitude')
    op.drop_constraint(None, 'Appareil', type_='foreignkey')
    op.create_foreign_key('Appareil_idCategorieAppareil_fkey', 'Appareil', 'Categorie_Appareil', ['idCategorieAppareil'], ['idCategorieAppareil'], ondelete='CASCADE')
    # ### end Alembic commands ###
