"""update site table

Revision ID: cd52db3bfdaf
Revises: 
Create Date: 2025-03-25 01:38:05.819009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd52db3bfdaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Secteur',
    sa.Column('idSecteur', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idSecteur')
    )
    op.create_index(op.f('ix_Secteur_idSecteur'), 'Secteur', ['idSecteur'], unique=False)
    op.create_table('Entreprise',
    sa.Column('idEntreprise', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('taille', sa.String(), nullable=False),
    sa.Column('certificat_propriete', sa.LargeBinary(), nullable=True),
    sa.Column('certificat_propriete_nom', sa.String(), nullable=True),
    sa.Column('statut_approbation', sa.String(), nullable=True),
    sa.Column('est_archive', sa.Boolean(), nullable=True),
    sa.Column('secteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secteur_id'], ['Secteur.idSecteur'], ),
    sa.PrimaryKeyConstraint('idEntreprise')
    )
    op.create_index(op.f('ix_Entreprise_idEntreprise'), 'Entreprise', ['idEntreprise'], unique=False)
    op.add_column('Site', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('Site', sa.Column('idEntreprise', sa.Integer(), nullable=True))
    op.add_column('Site', sa.Column('idResponsable', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Site', 'Entreprise', ['idEntreprise'], ['idEntreprise'])
    op.create_foreign_key(None, 'Site', 'users', ['idResponsable'], ['id'])
    op.drop_column('Site', 'longtitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Site', sa.Column('longtitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Site', type_='foreignkey')
    op.drop_constraint(None, 'Site', type_='foreignkey')
    op.drop_column('Site', 'idResponsable')
    op.drop_column('Site', 'idEntreprise')
    op.drop_column('Site', 'longitude')
    op.drop_index(op.f('ix_Entreprise_idEntreprise'), table_name='Entreprise')
    op.drop_table('Entreprise')
    op.drop_index(op.f('ix_Secteur_idSecteur'), table_name='Secteur')
    op.drop_table('Secteur')
    # ### end Alembic commands ###
