"""create appareil table

Revision ID: ddfe1629353f
Revises: b1368caaccc1
Create Date: 2025-02-26 12:53:34.041327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfe1629353f'
down_revision: Union[str, None] = 'b1368caaccc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categorie_Appareil',
    sa.Column('idCategorieAppareil', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idCategorieAppareil')
    )
    op.create_index(op.f('ix_Categorie_Appareil_idCategorieAppareil'), 'Categorie_Appareil', ['idCategorieAppareil'], unique=False)
    op.create_table('Appareil',
    sa.Column('idAppareil', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('marque', sa.String(), nullable=False),
    sa.Column('modele', sa.String(), nullable=False),
    sa.Column('puissance', sa.Float(), nullable=False),
    sa.Column('idCategorieAppareil', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCategorieAppareil'], ['Categorie_Appareil.idCategorieAppareil'], ),
    sa.ForeignKeyConstraint(['idUser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('idAppareil')
    )
    op.create_index(op.f('ix_Appareil_idAppareil'), 'Appareil', ['idAppareil'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Appareil_idAppareil'), table_name='Appareil')
    op.drop_table('Appareil')
    op.drop_index(op.f('ix_Categorie_Appareil_idCategorieAppareil'), table_name='Categorie_Appareil')
    op.drop_table('Categorie_Appareil')
    # ### end Alembic commands ###
