"""update site table

Revision ID: fdd4136b69c9
Revises: 
Create Date: 2025-03-22 04:59:52.089798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd4136b69c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Site', sa.Column('certificat_propriete', sa.LargeBinary(), nullable=True))
    op.add_column('Site', sa.Column('certificat_propriete_nom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Site', 'certificat_propriete_nom')
    op.drop_column('Site', 'certificat_propriete')
    # ### end Alembic commands ###
